webtalk_init -webtalk_dir D:/xixi/Image-Processing-master/Image-Processing-master/BIPT/BIPT.sim/sim_1/behav/xsim/xsim.dir/tb_modules_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 22 01:24:20 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f946ef31-1ffa-42bc-9cc6-76e21b594740" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ff3eb27d74514c27a4d7e091e02111b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "184040 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.33_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "28460_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1137166027 -regid "" -xml D:/xixi/Image-Processing-master/Image-Processing-master/BIPT/BIPT.sim/sim_1/behav/xsim/xsim.dir/tb_modules_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/xixi/Image-Processing-master/Image-Processing-master/BIPT/BIPT.sim/sim_1/behav/xsim/xsim.dir/tb_modules_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/xixi/Image-Processing-master/Image-Processing-master/BIPT/BIPT.sim/sim_1/behav/xsim/xsim.dir/tb_modules_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
